name: OPT LOGGING
on: [push, pull_request]
jobs:
    pipeline:
        name: librarie pipeline
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
        timeout-minutes: 40
        env:
            NODE_VERSION: 12.13.1
            SPRING_OUTPUT_ANSI_ENABLED: DETECT
            SPRING_JPA_SHOW_SQL: false
            JHI_DISABLE_WEBPACK_LOGS: true
            NG_CLI_ANALYTICS: false
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.13.1
            - uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - uses: actions/cache@v1
              with:
                  path: ~/.gradle/caches
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
                  restore-keys: |
                    ${{ runner.os }}-gradle-
            - name: Run backend test
              run: |
                  chmod +x gradlew
                  ./gradlew clean test integrationTest -x webpack
            - name: Analyze code with SonarQube
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
              run: |
                  if [ -n $SONAR_TOKEN ]; then
                      ./gradlew sonarqube --no-daemon -Dsonar.host.url=https://sonarcloud.io
                  else
                      echo No SONAR_TOKEN, skipping...
                  fi
            - name: Package application
              run: |
                  ./gradlew clean build --refresh-dependencies
                  ./gradlew createPom
            - name: Publish to GitHub Packages
              run: gradle publish
              env:
                USERNAME: ${{ github.actor }}
                PASSWORD: ${{ secrets.GITHUB_TOKEN }}
